# Black formatting
[tool.black]
line-length = 150
include = '\.pyi?$'
exclude = '''
/(
      .eggs         # exclude a few common directories in the
    | .git          # root of the project
    | .hg
    | .mypy_cache
    | .tox
    | venv
    | _build
    | buck-out
    | build
    | dist
    | shared_storage
    | logs
    | site
  )/
'''

# iSort
[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
virtual_env = "nlpvenv"

[tool.flake8]
exclude = "nlpvenv"
ignore = ["E501", "W503", "E226", "E731", "E203"]
# E501: Line too long
# W503: Line break occurred before binary operator
# E226: Missing white space around arithmetic operator
# E731: do not assign a lambda expression, use a def
# E203: Ignore slicing whitespace error

# Pytest
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

# Pytest cov
omit=["GPT/batch_predict.py", "seve.py", "config.py"]
